apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://kb-tempo:3200
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: tempo
      serviceMap:
        datasourceUid: tempo
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://kb-loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    editable: false