apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://kb_tempo:3200
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: tempo
      serviceMap:
        datasourceUid: tempo
    editable: false